[carbon_server]
baseurl = "https://localhost:9443"
hostname = "localhost"
username = "admin"
password = "admin"

[truststore]
absolute_path =  "/Users/rusirijayodaillesinghe/Documents/APIM_Repos/api-manager-3-2-x-swagger-tool/src/main/resources/security/client-truststore.jks"
password = "wso2carbon"

